# Generated by Django 3.0.5 on 2020-12-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_title_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.CharField(blank=True, help_text='Введите описание', max_length=50, verbose_name='Описание'),
        ),
    ]
